# Loss or Cost Function

In [1]:
# import paskages
import numpy as np

In [2]:
#data
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3 ,0.7 ,1,0,0.5])

In [3]:
#function  to calculate Mean Absoulate Error
def mae(y_true ,y_pred):
    total_error=0
    
    for yt ,yp ,in zip(y_true , y_pred):
        total_error += abs(yt -yp)
    print("Total Error :" , total_error)
    
    mae= total_error / len(y_true)
    print("MAE : ", mae)
    return mae

In [4]:
mae(y_true,y_predicted)

Total Error : 2.5
MAE :  0.5


0.5

### or

In [5]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [6]:
########################################################################

In [7]:
np.log([0]) #Not defined

C:\Users\DELL\AppData\Local\Temp\ipykernel_14816\3071246210.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0]) #Not defined


array([-inf])

In [8]:
np.log([0.000000000000000001])

array([-41.44653167])

In [9]:
epsilon = 1e-15

In [10]:
y_predicted_new =[max(i ,epsilon ) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [11]:
y_predicted_new = [min(i,1-epsilon ) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [12]:
y_predicted_new= np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [13]:
np.log(y_predicted)

C:\Users\DELL\AppData\Local\Temp\ipykernel_14816\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [14]:
-np.mean( y_true  * np.log(y_predicted_new) + (1-y_true)* np.log(1-y_predicted_new) )

17.2696280766844

In [15]:
#function log loss
epsilon =1e-15
def log_loss(y_true , y_predicted):
    y_predicted_new = [max(i,epsilon ) for i in y_predicted]
    
    y_predicted_new = [min(i ,1-epsilon ) for i in y_predicted_new]
    
    y_predicted_new=np.array(y_predicted_new)
    
    return -np.mean(  y_true *np.log(y_predicted_new) + (1-y_true) * np.log(1-y_predicted_new)       )

In [16]:
log_loss(y_true , y_predicted)

17.2696280766844