# Tensorflow Input Pipeline

In [1]:
#import paskages
import tensorflow as tf
import os

In [3]:
daily_sales_number =[21,22 ,-108 , 31 ,-1 , 32 ,34 ,31]

In [4]:
tf_dataset= tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [5]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [6]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [7]:
tf_dataset = tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [8]:
tf_dataset = tf_dataset.map(lambda x:x*72)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [9]:
def print_tensor(data):
    for sales in data.as_numpy_iterator():
        print(sales)

In [10]:
tf_dataset = tf_dataset.shuffle(3)
print_tensor(tf_dataset)

2232
1584
2448
1512
2304
2232


In [11]:
for sales_bath in tf_dataset.batch(2):
    print(sales_bath.numpy())

[1584 2304]
[2232 2448]
[2232 1512]


In [12]:
tf_dataset= tf_dataset.from_tensor_slices(daily_sales_number)
tf_dataset= tf_dataset.filter(lambda x:x>0).map(lambda y: y*72).shuffle(2).batch(2)

print_tensor(tf_dataset)

[1512 1584]
[2232 2448]
[2232 2304]


In [18]:
###########################################

In [13]:
images_ds = tf.data.Dataset.list_files("data/images/*/*/" , shuffle=False)

for f in images_ds.take(5):
    print(f.numpy())

b'data\\images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'data\\images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'data\\images\\cat\\A cat appears to have caught the....jpg'
b'data\\images\\cat\\Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'data\\images\\cat\\All About Your Cat_s Tongue.jpg'


In [14]:
images_ds = images_ds.shuffle(200)
for f in images_ds.take(3):
    print(f.numpy())

b'data\\images\\cat\\Reality check_ Can cat poop cause....jpg'
b'data\\images\\dog\\How To Read Your Dog_s Body Language....png'
b'data\\images\\dog\\Dogs caught coronavirus from their....jpg'


In [15]:
image_count = len(images_ds)
image_count

130

In [16]:
class_name =['cat','dog']

In [17]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [18]:
len(train_ds)

104

In [19]:
len(test_ds)

26

In [20]:
s="data\\images\\cat\\Soon_ the internet will make its own....jpg"
s.split("\\")[-2]

'cat'

In [21]:
def get_label(file_path):
    return tf.strings.split(file_path ,os.path.sep)[-2]

In [36]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path)
    img= tf.image.decode_jpeg(img)
    img= tf.image.resize(img ,[128 ,128])
    
    return img , label

In [38]:
for img,label in train_ds.map(process_image).take(3):
    print(label)

tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)


In [35]:
get_label("data\\images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")


<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [39]:
def scale(image ,  label):
    return image/255 ,label

In [41]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[237.       237.       237.      ]
  [237.       237.       237.      ]
  [237.       237.       237.      ]
  ...
  [204.3274   152.3274   105.32739 ]
  [196.55151  152.34058  107.41089 ]
  [206.70605  162.70605  117.706055]]

 [[237.       237.       237.      ]
  [237.       237.       237.      ]
  [237.       237.       237.      ]
  ...
  [197.75977  146.75977  101.759766]
  [203.83618  156.72632  114.75049 ]
  [208.47388  159.948    116.71094 ]]

 [[237.       237.       237.      ]
  [237.       237.       237.      ]
  [237.       237.       237.      ]
  ...
  [204.38525  157.32275  115.291504]
  [209.96338  158.26147  119.13086 ]
  [200.25073  148.28345  108.19116 ]]

 ...

 [[254.95312  254.95312  254.95312 ]
  [253.       253.       253.      ]
  [255.       255.       255.      ]
  ...
  [255.       255.       255.      ]
  [255.       255.       255.      ]
  [255.       255.       255.      ]]

 [[254.95312  254.95312  254.95312 ]
  [253.       253.   