# Word embedding using keras embedding layer 

In [1]:
#import paskages 
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

In [2]:
#data
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [13]:
one_hot("amazing restaurant",30)

[15, 26]

In [14]:
vocab_size=30
encoded_reviews = [one_hot(d , vocab_size) for d in reviews]
print(encoded_reviews)

[[11, 27], [15, 26], [22, 24], [13, 26, 3], [22, 18, 8], [23, 27], [16, 18, 2], [12, 13], [12, 17], [7, 1]]


In [38]:
max_length=3
padded_reviews = pad_sequences(encoded_reviews , maxlen=max_length , padding='post')
print(padded_reviews)

[[11 27  0]
 [15 26  0]
 [22 24  0]
 [13 26  3]
 [22 18  8]
 [23 27  0]
 [16 18  2]
 [12 13  0]
 [12 17  0]
 [ 7  1  0]]


In [39]:
embeded_vector_size = 5

In [40]:
model = Sequential([
    layers.Embedding(vocab_size  , embeded_vector_size , input_length=max_length , name='embedding'),
    layers.Flatten(),
    layers.Dense(1 , activation='sigmoid')
])

In [41]:
X = padded_reviews
y = sentiment

In [42]:
model.compile(optimizer='adam' ,loss='binary_crossentropy' , metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten_2 (Flatten)         (None, 15)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [43]:
history=model.fit(X,y , epochs=50 , verbose=0)

In [44]:
model.evaluate(X, y)

1/1 [==============================] - 0s 152ms/step - loss: 0.6051 - accuracy: 1.0000


[0.6051198840141296, 1.0]

In [45]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 29ms/step - loss: 0.6051 - accuracy: 1.0000


1.0

In [46]:
loss

0.6051198840141296

In [47]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30